name: fluttag
description: "ID3 Tag Editor for audio files"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  audiotags: ^1.4.5
  dex_compat:
    path: ../../packages/dex_compat
  file_picker: ^8.3.7
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  linux: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21
