name: fluttag
description: "ID3 Tag Editor for audio files"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  audiotags: ^1.4.5
  file_picker: ^8.3.7
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
